eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8085
spring:
  application:
    name: zp-feign
  main:
    allow-bean-definition-overriding: true

feign:
  hystrix:
    enabled: true

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  #MaxAutoRetries: 0
  #MaxAutoRetriesNextServer: 1


  thymeleaf:
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  #data:
    #solr:
      #host: http://localhost:8090/solr

  httpclient:
    enabled: true
